// Embeds assets/templates/*.md into lib/src/setup/templates.g.dart.
//
// `my-brain` ships as a single self-contained executable, so the files that
// `init` writes into a vault cannot be read from disk at runtime. They are
// kept as real markdown under assets/ (so they are reviewable and diffable)
// and compiled in as base64 constants — base64 rather than raw string literals
// so template content is never able to break out of its own quoting.
//
// Run: dart run tool/gen_templates.dart
import 'dart:convert';
import 'dart:io';

/// Template file -> the Dart constant it becomes.
const Map<String, String> _templates = {
  'AGENTS.md': 'agentsMdTemplate',
  'CLAUDE.md': 'claudeMdTemplate',
  'brain-capture.SKILL.md': 'brainCaptureSkillTemplate',
  'brain-maintain.SKILL.md': 'brainMaintainSkillTemplate',
};

void main() {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_templates.dart - do not edit.')
    ..writeln('// Edit the markdown under assets/templates/ and regenerate.')
    ..writeln('//')
    ..writeln('// These are the files `my-brain init` writes into a vault.')
    ..writeln("import 'dart:convert';")
    ..writeln();

  for (final entry in _templates.entries) {
    final file = File('assets/templates/${entry.key}');
    if (!file.existsSync()) {
      stderr.writeln('missing template: ${file.path}');
      exit(1);
    }
    final encoded = base64.encode(utf8.encode(file.readAsStringSync()));
    buffer
      ..writeln('/// Contents of `assets/templates/${entry.key}`.')
      ..writeln('final String ${entry.value} =')
      ..writeln("    utf8.decode(base64.decode('$encoded'));")
      ..writeln();
  }

  buffer
    ..writeln('/// Every template, keyed by its source filename. Lets `init`')
    ..writeln('/// iterate without hardcoding the set in two places.')
    ..writeln('final Map<String, String> allTemplates = {')
    ..writeAll(
      _templates.entries.map(
        (MapEntry<String, String> e) => "  '${e.key}': ${e.value},\n",
      ),
    )
    ..writeln('};');

  final out = File('lib/src/setup/templates.g.dart');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buffer.toString());
  stdout.writeln('wrote ${out.path} (${_templates.length} templates)');
}
